Add database
T0nystoyz/java-filmorate pull request #7
Opened 2022-07-16 19:42 UTC by T0nystoyz

Привет! В последние минуты все правил, главное тесты постмана прошли. Чуть позже косметический ремонт сделаю и тесты добавлю.

2022-07-17 13:22 UTC, kukolev requested changes

2022-07-17 13:22 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/GenreController.java
> +    private final GenreStorage genreStorage;
По условиям ТЗ контроллеры должны зависеть только от сервисов. Мапперы и хранилища должны быть внедрены в сервисы. Это позволяет логически отделить слой API от слоя бизнес-логики.

2022-07-17 13:22 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/MpaController.java
> +    private final MPADbStorage storage;
По условиям ТЗ контроллеры должны зависеть только от сервисов. Мапперы и хранилища должны быть внедрены в сервисы. Это позволяет логически отделить слой API от слоя бизнес-логики.

2022-07-17 13:22 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    Integer id;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-07-17 13:22 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    @Override
Переопределять методы equals и hashCode не нужно, если есть аннотация `@Data`. Эта аннотация обеспечивает добавление методов equals и hashCode на этапе компиляции.

2022-07-17 13:22 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        /*log.info("получен запрос на добавление в друзья пользователей c id {} и {}",
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-07-17 13:22 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        /*log.info("получен запрос на удаление из друзей ползователей с id {} и {}", id, friendId);
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-07-17 13:22 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        /*log.info("получен запрос на список друзей пользователя {}", storage.getById(id).getName());
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-07-17 13:22 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        /*if (storage.getById(id) == null) {
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-07-17 13:22 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +        final String sql = "INSERT INTO films (film_id, name, description, release_date, duration, mpa_id)"
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-17 13:22 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FriendshipDbStorage.java
> +        final String sql = "SELECT friend_id FROM FRIENDSHIPS WHERE user_id = ?";
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-17 13:22 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/GenreDbStorage.java
> +        final String sql = "SELECT * FROM genres ORDER BY GENRE_ID";
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-17 13:22 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/LikeDbStorage.java
> +        final String sql = "SELECT * FROM films f LEFT JOIN (SELECT film_id, COUNT(*) likes_count FROM likes"
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-17 13:22 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/MPADbStorage.java
> +        final String sql = "SELECT * FROM MPA";
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-17 13:22 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/UserDbStorage.java
> +        final String sql = "SELECT * FROM USERS";
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-19 17:16 UTC, kukolev requested changes

2022-07-19 17:16 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    @Override
Если нет желания использовать `@Data`, то можно добавить аннотацию `@EqualsAndHashcode` и удалить переопределенные методы, т.к. смысла в них нет.

2022-07-19 19:19 UTC, T0nystoyz commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    @Override
Смысл в том, что с автоматически генерируемыми, в постман не проходит тест. Не в том порядке выдаётся список с жанрами. А тут я переопределил чтобы он сравнивал только по айди, и сработало

2022-07-19 19:21 UTC, T0nystoyz commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    @Override
Может конечно прчиина не в этом, я много экспериментировал. И этот способ помог.

2022-07-20 17:10 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    @Override
Это хорошо. Теперь нужно сделать коммит и пуш, т.к. код еще не поменялся )

2022-07-20 17:11 UTC, kukolev requested changes

2022-07-20 17:11 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    public boolean equals(Object o) {
Нужно сделать коммит и пуш, т.к. код еще не поменялся

2022-07-25 07:24 UTC, kukolev approved these changes

2022-07-27 10:59 UTC, merged